<?php
require_once("zaklad.php");
require_once (dirname(__DIR__).'/kontrolery/Kontroler.php');
require_once (dirname(__DIR__).'/kontrolery/SmerovacKontroler.php');
require_once (dirname(__DIR__).'/kontrolery/AboutKontroler.php');
session_start();
$smer= new SmerovacKontroler();
$smer->zkontroluj(array($_SERVER['REQUEST_URI']));
$smer = $smer->kontroler;

$succ = null;
$error = null;
if($_SERVER["REQUEST_METHOD"] == "POST") {
    if($_SESSION["rule"]==1){
        $smer->update();
        $smer= new SmerovacKontroler();
        $smer->zkontroluj(array($_SERVER['REQUEST_URI']));
        $smer = $smer->kontroler;
        $succ="Nyní jste spisovatelem.";
    } elseif ($_SESSION["rule"]>1){$error="Již jste spisovatelem nebo adminem.";}
}
echo zaklad::allIn();
?>

    <html>
    <body>
    <div class="containerful">

        <div class="content nopad">
            <?php
            echo zaklad::leveMenu();
            ?>
            <div id="staticcontent">



                <h3>O konferenci:</h3>

                <p>Toto je konference vytvořená jako semestrální práce pro předmět KIV/WEB.</p>
                <p>Uživatelé mohou být tří typů: </p>
                <p>Čtenáři, kteří mohou jen číst nejlepší články.</p>
                <p>Spisovatelé, kteří mají k dispozici všechny články, můžou psát nové a hodnotit články.</p>
                <p>A admini, kteří můžou navíc spravovat všechny články a uživatele.</p>
                <p>Chcete-li se stát spisovateli, klidněte na následující tlačítko.</p>

                <form action = "" method = "post">
                <input type="submit" class="btn btn-success btn-lg float-right" name="update" value="Stát se spisovatelem." />
                </form>
                <div style = "font-size:11px; color:#cc0000; margin-top:10px"><?php echo $error; ?></div>
                <div style = "font-size:16px; color:#5aeb86; margin-top:10px"><?php echo $succ; ?></div>
            </div>
        </div>
    </div>
    </body>

    </html>

<?php
echo zaklad::spodek();

?>