<?php
require("zaklad.php");
require_once (dirname(__DIR__).'/kontrolery/SmerovacKontroler.php');
require_once (dirname(__DIR__).'/kontrolery/ClankyKontroler.php');
require_once (dirname(__DIR__).'/kontrolery/Kontroler.php');
session_start();
$smer= new SmerovacKontroler();
$smer->zkontroluj(array($_SERVER['REQUEST_URI']));
$smer = new ClankyKontroler();
$sql = $smer->getClanky();

echo zaklad::allIn();

?>

<html>
<body>
<div class="containerful">

    <div class="content nopad">
        <?php
        echo zaklad::leveMenu();
        ?>
        <div id="staticcontent">


            <h3>K dispozici jsou následující články:</h3>

            <?php

            foreach ($sql as $clanek){
                echo '<div class="containerclanek"><h5> '. $clanek["clanek"].'</h5>
            <h6>Uživatel: '. $clanek["user"].' 
              Rating:  '. $clanek["rating"].'
              <a target="_blank" href="../uploads/'.$clanek["file"].'" class="btn btn-sm btn-primary float-right" >Stáhnout příspěvek</a></h6>
            <p>
               Popis:  '. $clanek["desc"].'</p>
              <p>  
                
            </p></div>';
            }

            ?>


        </div>
    </div>
</div>
</body>

</html>

<?php
echo zaklad::spodek();

?>


