<?php
require("zaklad.php");
require_once (dirname(__DIR__).'/kontrolery/SmerovacKontroler.php');
require_once (dirname(__DIR__).'/kontrolery/KomentareKontroler.php');
require_once (dirname(__DIR__).'/kontrolery/Kontroler.php');
session_start();
$smer= new SmerovacKontroler();
$smer->zkontroluj(array($_SERVER['REQUEST_URI']));
$smer = $smer->kontroler;
$comment = $smer->getKomentare();
$art = $smer->getArticle();

echo zaklad::allIn();

if($_SERVER["REQUEST_METHOD"] == "POST") {
    $smer->insertKoment( $art["id"], $_POST['head'],$_POST['value'],$_POST['body']);
    $comment = $smer->getKomentare();
    $art = $smer->getArticle();
}

?>

<html>
<body>
<div class="containerful">

    <div class="content nopad">
        <?php
        echo zaklad::leveMenu();
        ?>
        <div id="staticcontent">


            <a title="Zpět na seznam příspěvků" href="../prispevky">Zpět na seznam</a>

            <div class="callout" style="margin-top: 1em;">


            <?php
            echo '<h5>'.$art["clanek"].'</h5>
                <h6>Autoři: '.$art["user"].'</h6>
                <h7>Hodnocení: '.$smer->getRating($art["id"])["rating"].'</h7>
                <p title="Popis článku">'.$art["desc"].'</p>
                <p><a target="_blank" href="../../uploads/'.$art["file"].'" title="Stáhnout příspěvek '.$art["clanek"].'">Stáhnout</a></p>
            </div>';

            foreach ($comment as $com){
                echo '<div class="containerclanek">
            <h6>Nadpis: '.$com["head"].' 
            Uživatel: '. $com["name"].' 
              Hodnocení:  '. $com["value"].'</h6>
            <p>
               Komentář:  '. $com["body"].'</p>
              <p>  
                
            </p></div>';
            }
            ?>

                <div style = " border: solid 1px #333333; " align = "left">
                    <div style = "background-color:#333333; color:#FFFFFF; padding:3px;"><b>Nový komentář</b></div>

                    <div style = "margin:10px">

                        <form action = "" method = "post">
                            <label>Nadpis  <span class="required"></span>:</label><input type = "text" name = "head" class = "box"/><br /><br />
                            <label>Hodnocení  <span class="required"></span>:</label><input type = "number" name = "value" class = "box" style="width: 4em"/><br/><br />
                            <label style="margin-top: -3rem">Komentář  <span class="required"></span>:</label><textarea name="body" style="height: 200px"></textarea><br/><br />
                            <div class="row">
                                <div class="large-12 columns">
                                    <span class="required"></span> - povinná položka
                                    <input type="submit" class="button success float-right" name="save" value="Uložit a odeslat" />
                                </div>
                            </div>
                        </form>

                    </div>

                </div>


        </div>
    </div>
</div>
</body>

</html>

<?php
echo zaklad::spodek();

?>


