<?php
require_once("zaklad.php");
require_once (dirname(__DIR__).'/modely/Users.php');
require_once (dirname(__DIR__).'/kontrolery/Kontroler.php');
require_once (dirname(__DIR__).'/kontrolery/SmerovacKontroler.php');
require_once (dirname(__DIR__).'/kontrolery/UvodKontroler.php');
session_start();

//echo zaklad::spodek();
$_SESSION["request"]=$_SERVER['REQUEST_URI'];
$smer= new SmerovacKontroler();
$smer->zkontroluj(array($_SERVER['REQUEST_URI']));
echo zaklad::allIn();
if(!empty($_SESSION['login'])){$smer->prejdi("web2/view/uvod");/*Kontroler::presmeruj("uvod");*/}
$error=null;
if($_SERVER["REQUEST_METHOD"] == "POST") {
    $_SESSION['sakra']="hej";
    Users::login($_POST['username'],$_POST['password']);
if(!empty($_SESSION['login'])){$error=null; $smer->prejdi("web2/view/uvod");/*Kontroler::presmeruj("uvod");*/}
else{$error = "Jméno nebo heslo bylo zadáno špatně.";}
}
?>


<html>



<body>
   <h1>Vítejte na portálu!</h1>


   <div align = "center">
         <div style = "width:300px; border: solid 1px #333333; " align = "left">
            <div style = "background-color:#333333; color:#FFFFFF; padding:3px;"><b>Login</b></div>

            <div style = "margin:10px">

               <form action = "" method = "post">
                  <label>Uživatelské jméno  :</label><input type = "text" name = "username" class = "box"/><br /><br />
                  <label>Heslo  :</label><input type = "password" name = "password" class = "box" /><br/><br />
                  <input type = "submit" value = " Přihlásit "/><br />
               </form>
                <div style = "font-size:11px; color:#cc0000; margin-top:10px"><?php echo $error; ?></div>

            </div>

</div>

</div>


</body>
</html>
