<?php
require("zaklad.php");
require_once (dirname(__DIR__).'/kontrolery/SmerovacKontroler.php');
require_once (dirname(__DIR__).'/kontrolery/LogoutKontroler.php');
require_once (dirname(__DIR__).'/kontrolery/Kontroler.php');
session_start();
$smer= new SmerovacKontroler();
$smer->zkontroluj(array($_SERVER['REQUEST_URI']));
unset($_SESSION["login"]);
unset($_SESSION["rule"]);

echo zaklad::allIn();

?>

    <html>
    <body>
    <div class="containerful">

        <div class="content nopad">
            <?php
            echo zaklad::leveMenu();
            ?>
            <div id="staticcontent">



                <h3>Byli jste úspěšně odhlášeni!</h3>

                <p><a href = "login">Přihlásit</a></p>

            </div>
        </div>
    </div>
    </body>

    </html>

<?php
echo zaklad::spodek();

?>