<!DOCTYPE html>
<html lang="cs-cz">
	<head>
		<base href="/localhost" />
		<meta charset="UTF-8" />
		<title><?= $titulek ?></title>
		<meta name="description" content="<?= $popis ?>" />
		<meta name="keywords" content="<?= $klicova_slova ?>" />
		<link rel="stylesheet" href="style.css" type="text/css"/>
        <link href="{{ base_url }}/css/foundation.min.css" rel="stylesheet" />
        <link href="{{ base_url }}/css/main.css" rel="stylesheet" />
	</head>

	<body>
		<header>
			<h1>DevbookMVC - ukázkový web</h1>
		</header>

        <div class="content nopad">
            <div id="leftmenu">
                <a title="Titulní strana" href="{{ link('/') }}" class="item">Titulní strana</a>
                <a title="O konferenci" href="{{ link('/homepage/aboutconf') }}" class="item">O konferenci</a>
                <a title="Témata" href="{{ link('/homepage/topics') }}" class="item">Témata</a>
                <a title="Termíny" href="{{ link('/homepage/dates') }}" class="item">Termíny</a>
                <a title="Organizátoři" href="{{ link('/homepage/team') }}" class="item">Organizátoři</a>
                <a title="Čas a místo konání" href="{{ link('/homepage/place') }}" class="item">Čas a místo konání</a>
                <a title="Sponzoři" href="{{ link('/homepage/sponsors') }}" class="item">Sponzoři</a>
                <a title="Pokyny pro autory" href="{{ link('/homepage/authorinfo') }}" class="item">Pokyny pro autory</a>

                <a title="Uživatelský panel" class="item" href="{{ link('/dashboard/') }}{{ user['role'] }}">Uživatelský panel</a>

                <a title="Přihlásit se" class="item" href="{{ link('/sign/in') }}">Přihlásit se</a>

            </div>

		<nav>
			<ul>
				<li><a href="clanek/uvod">Úvod</a></li>
				<li><a href="clanek">Články</a></li>
				<li><a href="kontakt">Kontakt</a></li>			
			</ul>
		</nav>
		<br clear="both" />
		
		<article>
			<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
		</article>
		
		<footer>
			<p>Ukázkový tutoriál pro jednoduché MVC z programátorské sociální sítě 
			<a href="http://www.devbook.cz" target="_blank">devbook.cz</a>.</p>
		</footer>
	</body>
</html>