<?php
require_once("zaklad.php");
require_once (dirname(__DIR__).'/kontrolery/Kontroler.php');
require_once (dirname(__DIR__).'/kontrolery/SmerovacKontroler.php');
require_once (dirname(__DIR__).'/kontrolery/UvodKontroler.php');
session_start();
$smer= new SmerovacKontroler();
$smer->zkontroluj(array($_SERVER['REQUEST_URI']));
echo zaklad::allIn();

?>

<html>
<body>
<div class="containerful">

    <div class="content nopad">
        <?php
        echo zaklad::leveMenu();
        ?>
<div id="staticcontent">



<h3>Vítejte na portálu!</h3>

    <p>Vítejte na zbrusu novém portálu webové pseudokonference, který byl vyvinutý v rámci semestrální práce předmětu Webové aplikace (KIV/WEB)</p>

    <p>V levém menu můžete najít odkazy do sekcí obsahujících všechny potřebné informace. V případě nejasností můžete psát e-mail na adresu <a href="mailto:zabran@students.zcu.cz">zabran@students.zcu.cz</a>.</p>
</div>
</div>
</div>
</body>

</html>

<?php
echo zaklad::spodek();

?>